name: build-commit

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "changelog.md"
      - "beta-changelog.md"
      - "features.md"
      - ".editorconfig"
      - "src/*/resources/lang/*"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "beta-changelog.md"
      - "features.md"
      - ".editorconfig"
      - "src/*/resources/lang/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Gradle

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        uses: Wandalen/wretry.action@master
        with:
          command: ./gradlew buildAllVersions --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          path: versions/**/build/libs/*.jar