name: sync-readme

on:
  push:
    paths:
      - "README.md"
    branches:
      - main
  workflow_dispatch:

jobs:
  modrinth-description:
    runs-on: ubuntu-latest
    name: Sync Modrinth description
    steps:
      - uses: actions/checkout@v4
      - uses: funnyboy-roks/modrinth-auto-desc@v1.6
        with:
          auth-token: ${{ secrets.MODRINTH_API_KEY }}
          slug: 'skylper'